/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.IF20A.View20312067;

import com.IF20A.ControlInterface20312067.InterfaceBuku20312067;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.IF20A.Model20312067.MBuku20312067;
import com.IF20A.ControlImplement20312067.ImplementBuku20312067;
import com.IF20A.Model20312067.MPenerbit20312067;
import com.IF20A.Model20312067.MPenagarang20312067;
import com.IF20A.Model20312067.MKategori20312067;
/**
 *
 * @author ramanda
 */
public class VBuku20312067 extends javax.swing.JFrame {
    List<MBuku20312067> record = new ArrayList<>();
    InterfaceBuku20312067 bukuservice;
    List<MKategori20312067> kat = new ArrayList<>();
    List<MPenagarang20312067> png = new ArrayList<>();
    List<MPenerbit20312067> pnb = new ArrayList<>();
    int row;
    
    void panggildata(){
        try {
            record = bukuservice.tampilBuku_20312067();
        } catch(Exception e) {
            
        }
    }
    
    void isitabel(){
        Object data[][] = new Object[record.size()][11];
        int x = 0;
        for(MBuku20312067 buku : record){
            data[x][0] = buku.getISBN20312067();
            data[x][1] = buku.getJudul20312067();
            data[x][2] = buku.getIDPengarang20312067();
            data[x][3] = buku.getNamaPengarang20312067();
            data[x][4] = buku.getIDPenerbit20312067();
            data[x][5] = buku.getNamaPenerbit20312067();
            data[x][6] = buku.getIDKategori20312067();
            data[x][7] = buku.getNamaKategori20312067();
            data[x][8] = buku.getHarga20312067();
            data[x][9] = buku.getTahun20312067();
            data[x][10] = buku.getStok20312067();
            x++;
        }
        String judul[] = {"ISBN", "Judul", "ID Pengarang", "Nama Pengarang", "ID Penerbit", "Nama Penerbit", "ID Kategori", "Nama Kategori", "Harga", "Tahun", "Stok"};
        jtbuku.setModel(new DefaultTableModel(data, judul));
    }
    
    void refreshdata(){
        panggildata();
        isitabel();
    }
    
    void bersih(){
        EDISBN.setText("");
        EDJudul.setText("");
        EDHarga.setText("");
        EDTahun.setText("");
        EDStok.setText("");
        EDISBN.setEnabled(true);
        EDISBN.requestFocus();
    }
    
    void getPenerbit(){
        try{
            pnb = bukuservice.tampilPenerbit_20312067();
        } catch (Exception e) {
            
        }
        for (MPenerbit20312067 mPenerbit20312067 : pnb) {
            jcbPnb.addItem(mPenerbit20312067.getPenerbitNama20312067());
        }
    }
    void getPengarang(){
        try{
            png = bukuservice.tampilPengarang_20312067();
        } catch (Exception e) {
            
        }
        for (MPenagarang20312067 mPengarang : png) {
            jcbPng.addItem(mPengarang.getPengarangNama20312067());
        }
    }
    void getKategori(){
        kat = new ArrayList<>();
        try{
            kat = bukuservice.tampilKategori_20312067();
        } catch (Exception e) {
            
        }
        for (MKategori20312067 mKategori : kat) {
            jcbKtg.addItem(mKategori.getKategoriNama20312067());
        }
    }
    
    /**
     * Creates new form VBuku20312067
     */
    public VBuku20312067( ) {
        initComponents();
        bukuservice = new ImplementBuku20312067();
        getPenerbit();
        getPengarang();
        getKategori();
        this.refreshdata();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EDISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EDJudul = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EDHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EDTahun = new javax.swing.JTextField();
        EDStok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBaru = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbuku = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EDNamaPenerbit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EDidPenerbit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EDNamaPengarang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        EDIdPengarang = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        EDNamaKategori = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        EDIdKategori = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        jcbPnb = new javax.swing.JComboBox<>();
        jcbPng = new javax.swing.JComboBox<>();
        jcbKtg = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORM DATA BUKU");

        jLabel1.setText("ISBN");

        EDISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDISBNActionPerformed(evt);
            }
        });

        jLabel2.setText("Data Buku");

        jLabel3.setText("Judul Buku");

        jLabel4.setText("Harga");

        jLabel5.setText("Tahun Terbit");

        jLabel6.setText("Stok");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        jtbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbuku);

        jLabel7.setText("Data Penerbit");

        jLabel8.setText("Nama Penerbit");

        jLabel9.setText("ID Penerbit");

        jLabel10.setText("Data Pengarang");

        jLabel11.setText("Nama Pengarang");

        jLabel12.setText("ID Pengarang");

        jLabel13.setText("Data Kategori");

        jLabel14.setText("Nama Kategori");

        jLabel15.setText("ID Kategori");

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        jcbPnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPnbActionPerformed(evt);
            }
        });

        jcbPng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPngActionPerformed(evt);
            }
        });

        jcbKtg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbKtgFocusLost(evt);
            }
        });
        jcbKtg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbKtgMouseClicked(evt);
            }
        });
        jcbKtg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbKtgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCetak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EDStok, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EDTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EDHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EDISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(38, 38, 38)
                                    .addComponent(EDJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EDidPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(51, 51, 51)
                                .addComponent(EDNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(59, 59, 59)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EDIdPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EDNamaPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(51, 51, 51)
                                .addComponent(EDNamaPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(72, 72, 72)
                                .addComponent(EDIdKategori)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbPnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbPng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbKtg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDidPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbPnb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDNamaPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDIdPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jcbPng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDNamaPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDIdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jcbKtg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDNamaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EDStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBaru)
                            .addComponent(btnBatal)
                            .addComponent(btnSimpan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKeluar)
                            .addComponent(btnHapus)
                            .addComponent(btnCetak))
                        .addGap(39, 39, 39)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
       if(JOptionPane.showConfirmDialog(null, "Yakin Keluar dari form buku?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            bukuservice.hapus_20312067(EDISBN.getText());
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
            this.refreshdata();
            this.bersih();
        } catch(Exception e){

        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        MBuku20312067 o = new MBuku20312067();
        
        o.setISBN20312067(EDISBN.getText());
        o.setJudul20312067(EDJudul.getText());
        o.setHarga20312067(Integer.parseInt(EDHarga.getText()));
        o.setStok20312067(Integer.parseInt(EDStok.getText()));
        o.setIDPenerbit20312067(EDidPenerbit.getText());
        o.setIDPengarang20312067(EDIdPengarang.getText());
        o.setIDKategori20312067(EDIdKategori.getText());
        o.setTahun20312067(EDTahun.getText());
        
        try{
            bukuservice.simpanBuku_20312067(o);
        } catch (Exception e){
            
        }
        
        this.refreshdata();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCetakActionPerformed

    private void jcbPnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPnbActionPerformed
        // TODO add your handling code here:
        EDNamaPenerbit.setText(jcbPnb.getSelectedItem().toString());
        for (MPenerbit20312067 mPenerbit : pnb) {
            if(jcbPnb.getSelectedItem().toString().equals(mPenerbit.getPenerbitNama20312067())){
                EDidPenerbit.setText(mPenerbit.getPenerbitId20312067());
            }
            
        }
        EDidPenerbit.setEnabled(false);
    }//GEN-LAST:event_jcbPnbActionPerformed

    private void jcbPngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPngActionPerformed
        // TODO add your handling code here:
        EDNamaPengarang.setText(jcbPng.getSelectedItem().toString());
        for (MPenagarang20312067 mPengarang : png) {
            if(jcbPng.getSelectedItem().toString().equals(mPengarang.getPengarangNama20312067())){
                EDIdPengarang.setText(mPengarang.getPengarangId20312067());
            }
            
        }
        EDIdPengarang.setEnabled(false);
    }//GEN-LAST:event_jcbPngActionPerformed

    private void jcbKtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbKtgActionPerformed
        // TODO add your handling code here:
        EDNamaKategori.setText(jcbKtg.getSelectedItem().toString());
        for (MKategori20312067 mKategori : kat) {
            if(jcbKtg.getSelectedItem().toString().equals(mKategori.getKategoriNama20312067())){
                EDIdKategori.setText(mKategori.getKategoriId20312067());
            }
            
        }
        EDIdKategori.setEnabled(false);
    }//GEN-LAST:event_jcbKtgActionPerformed

    private void jcbKtgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbKtgMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbKtgMouseClicked

    private void jcbKtgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbKtgFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbKtgFocusLost

    private void jtbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbukuMouseClicked
        // TODO add your handling code here:
        if(jtbuku.getSelectedColumnCount() == 1){
            int rows = jtbuku.getSelectedRow();
            EDISBN.setText(jtbuku.getValueAt(rows, 0).toString());
            EDJudul.setText(jtbuku.getValueAt(rows, 1).toString());
            EDHarga.setText(jtbuku.getValueAt(rows, 8).toString());
            EDTahun.setText(jtbuku.getValueAt(rows, 9).toString());
            EDStok.setText(jtbuku.getValueAt(rows, 10).toString());
            EDidPenerbit.setText(jtbuku.getValueAt(rows, 4).toString());
            EDNamaPenerbit.setText(jtbuku.getValueAt(rows, 5).toString());
            EDIdPengarang.setText(jtbuku.getValueAt(rows, 2).toString());
            EDNamaPengarang.setText(jtbuku.getValueAt(rows, 3).toString());
            EDIdKategori.setText(jtbuku.getValueAt(rows, 6).toString());
            EDNamaKategori.setText(jtbuku.getValueAt(rows, 7).toString());
            
            EDISBN.setEnabled(false);
        }
    }//GEN-LAST:event_jtbukuMouseClicked

    private void EDISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDISBNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VBuku20312067.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VBuku20312067.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VBuku20312067.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VBuku20312067.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VBuku20312067().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EDHarga;
    private javax.swing.JTextField EDISBN;
    private javax.swing.JTextField EDIdKategori;
    private javax.swing.JTextField EDIdPengarang;
    private javax.swing.JTextField EDJudul;
    private javax.swing.JTextField EDNamaKategori;
    private javax.swing.JTextField EDNamaPenerbit;
    private javax.swing.JTextField EDNamaPengarang;
    private javax.swing.JTextField EDStok;
    private javax.swing.JTextField EDTahun;
    private javax.swing.JTextField EDidPenerbit;
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbKtg;
    private javax.swing.JComboBox<String> jcbPnb;
    private javax.swing.JComboBox<String> jcbPng;
    private javax.swing.JTable jtbuku;
    // End of variables declaration//GEN-END:variables
}
